name = "mist"
version = "0.15.0"

licences = ["Apache-2.0"]
description = "a misty Gleam web server"
repository = { type = "github", user = "rawhat", repo = "mist" }
target = "erlang"
gleam = ">= 0.33.0"

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_erlang = "~> 0.23"
gleam_http = "~> 3.5"
gleam_otp = "~> 0.8"
glisten = { path = "../glisten" }
hpack_erl = "~> 0.3"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_hackney = "~> 1.2"
